export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const CLOSE_SIGNUP_MODAL = 'CLOSE_SIGNUP_MODAL';

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';

export const SHOW_PROPERTY_FORM_MODAL = 'SHOW_PROPERTY_FORM_MODAL';
export const CLOSE_PROPERTY_FORM_MODAL = 'CLOSE_PROPERTY_FORM_MODAL';

export const SHOW_PROPERTY_REVIEW_MODAL = 'SHOW_PROPERTY_REVIEW_MODAL';
export const CLOSE_PROPERTY_REVIEW_MODAL = 'CLOSE_PROPERTY_REVIEW_MODAL';

export const SHOW_PROPERTY_DROPZONE_MODAL = 'SHOW_PROPERTY_DROPZONE_MODAL';
export const CLOSE_PROPERTY_DROPZONE_MODAL = 'CLOSE_PROPERTY_DROPZONE_MODAL';