export const GET_AUTH_USER = 'GET_AUTH_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_ROLE_TO_HOST = 'UPDATE_USER_ROLE_TO_HOST';

export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_ERROR';
