export const GET_ALL_PROPERTIES = 'GET_ALL_PROPERTIES';
export const GET_SINGLE_PROPERTY = 'GET_SINGLE_PROPERTY';
export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const GET_CURRENT_PROPERTY = 'GET_CURRENT_PROPERTY';
export const CLEAR_CURRENT_PROPERTY = 'CLEAR_CURRENT_PROPERTY';


export const PROPERTY_ERROR = 'PROPERTY_ERROR';
export const CLEAR_PROPERTY_ERROR = 'CLEAR_PROPERTY_ERROR';
