

/*** 
 * PROPERTY TYPES
 ***/


export const GET_HOMEPAGE_PROPERTIES = 'GET_HOMEPAGE_PROPERTIES';
export const GET_ALL_PROPERTIES = 'GET_ALL_PROPERTIES';
export const GET_SINGLE_PROPERTY = 'GET_SINGLE_PROPERTY';
export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const GET_CURRENT_PROPERTY = 'GET_CURRENT_PROPERTY';
export const CLEAR_CURRENT_PROPERTY = 'CLEAR_CURRENT_PROPERTY';


export const PROPERTY_ERROR = 'PROPERTY_ERROR';
export const CLEAR_PROPERTY_ERROR = 'CLEAR_PROPERTY_ERROR';



/*** 
 * PROPERTY REVIEW TYPES
 ***/

export const GET_ALL_PROPERTY_REVIEW = 'GET_ALL_PROPERTY_REVIEW';
export const GET_SINGLE_PROPERTY_REVIEW = 'GET_SINGLE_PROPERTY_REVIEW';
export const CREATE_PROPERTY_REVIEW = 'CREATE_PROPERTY_REVIEW';
export const UPDATE_PROPERTY_REVIEW = 'UPDATE_PROPERTY_REVIEW';
export const DELETE_PROPERTY_REVIEW = 'DELETE_PROPERTY_REVIEW';
export const GET_CURRENT_PROPERTY_REVIEW = 'GET_CURRENT_PROPERTY_REVIEW';
export const CLEAR_CURRENT_PROPERTY_REVIEW = 'CLEAR_CURRENT_PROPERTY_REVIEW';

export const PROPERTY_REVIEW_ERROR = 'PROPERTY_REVIEW_ERROR';
export const CLEAR_PROPERTY_REVIEW_ERROR = 'CLEAR_PROPERTY_REVIEW_ERROR';

